version: '3.7'

services:
  postgres:
    container_name: postgres-products
    image: postgres:12
    volumes:
      - psql-products-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: products_api
      POSTGRES_USER: ote
      POSTGRES_PASSWORD: secret

  api:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - postgres

volumes:
  psql-products-data: